### ISSUE TITLE
Cardona Node Started Panicking

### ISSUE THREAD

**Issue by hdiass** [0xPolygon/cdk-erigon#1183]
#### System information
Node crashed while it was in sync. Now can't boot normally showing this error 

Erigon version: `./erigon --version`

v1.2.15.7 and v2.0.0-beta18.3

OS & Version: Windows/Linux/OSX

Commit hash:  

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: Cardona

#### Expected behaviour
Sync normally

#### Steps to reproduce the behaviour
Node was normally running and then this happenend and node keeps on crashing

#### Backtrace

````
[INFO] [09-16|14:38:32.466] [2/16 L1InfoTree] Starting L1 Info Tree stage
[INFO] [09-16|14:38:32.467] Starting L1 syncer thread
[INFO] [09-16|14:38:32.651] [2/16 L1InfoTree] Info tree updates      count=0
[INFO] [09-16|14:38:32.651] [2/16 L1InfoTree] Finished L1 Info Tree stage
[INFO] [09-16|14:38:32.651] [3/16 Batches] Starting batches stage
[INFO] [09-16|14:38:32.651] [3/16 Batches] Starting stream           startBlock=6701843
[INFO] [09-16|14:38:32.651] [3/16 Batches] Execution behind, skipping stage
[INFO] [09-16|14:38:32.651] [3/16 Batches] Started downloading L2Blocks routine
[INFO] [09-16|14:38:32.651] [3/16 Batches] Finished Batches stage
[INFO] [09-16|14:38:32.651] [4/16 BlockHashes] Etl transform started
[INFO] [09-16|14:38:32.654] [4/16 BlockHashes] Etl transform ended
[INFO] [09-16|14:38:32.655] [6/16 Execution] Short circuit           batch=125276 block=6701809
[INFO] [09-16|14:38:32.655] [6/16 Execution] Blocks execution        from=6701808 to=6701809
[INFO] [09-16|14:38:32.657] [6/16 Execution] Commiting DB transaction... block=6701809
[INFO] [09-16|14:38:32.673] [6/16 Execution] Completed on            block=6701809
[INFO] [09-16|14:38:32.673] [7/16 CumulativeIndex] Started
[INFO] [09-16|14:38:32.673] [7/16 CumulativeIndex] Finished
[INFO] [09-16|14:38:32.673] [8/16 HashState] Started
[INFO] [09-16|14:38:32.677] [8/16 HashState] Finished
[INFO] [09-16|14:38:32.677] [9/16 IntermediateHashes] Generating intermediate hashes from=6701626 to=6701809
[INFO] [09-16|14:38:32.677] [9/16 IntermediateHashes] SMT not using mapmutation
[INFO] [09-16|14:38:32.677] [9/16 IntermediateHashes] Increment trie hashes started previousRootHeight=6701626 calculatingRootHeight=6701809
[INFO] [09-16|14:38:34.752] [9/16 IntermediateHashes] Regeneration trie hashes finished. Commiting batch
[INFO] [09-16|14:38:34.752] [9/16 IntermediateHashes] Increment ended
[INFO] [09-16|14:38:34.752] [9/16 IntermediateHashes] Trie root      hash=0x4f6dc50576928fdea7fcf13d88707a9856b314c1c26ce8f6b30d18b326590a84
panic: [9/16 IntermediateHashes] Wrong trie root of block 6701809: 4f6dc50576928fdea7fcf13d88707a9856b314c1c26ce8f6b30d18b326590a84, expected (from header): 0b6a073a5416c4cff4cb0ea142e6fc1f1405544aa765de95fbec11451f0758ed. Block hash: 740128518fc54a008cf8dbef78338962802c3f289f91413e61fb5113d4350507

goroutine 61 [running]:
github.com/ledgerwatch/erigon/zk/stages.SpawnZkIntermediateHashesStage(0xc001c2d0c0, {0x2f16d98?, 0xc00005e070?}, {0x0, 0x0}, {{0x2f297b8, 0xc00193a000}, 0x1, 0x0, {0xc001953220, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/zk/stages/stage_interhashes.go:173 +0x125f
github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func25(0x60?, 0x1?, 0x2782874?, {0x2efe960?, 0xc0044c0160?}, {0x0?, 0x0?}, 0x0?)
        github.com/ledgerwatch/erigon/zk/stages/stages.go:379 +0x93
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0044c0160, 0xc001c1e140, {0x2f297b8?, 0xc00193a000}, {0x0?, 0x0}, 0x50?, 0x1?, 0x18?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:360 +0x16d
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0044c0160, {0x2f297b8, 0xc00193a000}, {0x0, 0x0}, 0x2?, 0x0?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:262 +0x285
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2f16d60?, 0xc0011d4190}, 0x0?, {0x2f297b8, 0xc00193a000}, 0xc0044c0160, 0xc0009b4420, 0x1, 0xc000300250)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:177 +0x46d
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2f16d60, 0xc0011d4190}, 0x0?, {0x2f297b8?, 0xc00193a000}, 0xdb4bae?, 0xc0011c9440, 0x7f08272134e8?, 0xc00111cde0?, 0xc0011d6000, ...)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:97 +0x165
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:1422 +0x225

````

**Comment by V-Staykov** [comment]
Was the innitial crash with the same error?

**Comment by icculp** [comment]
I had the same issue, tried both versions, also tried resync from scratch with v1.2.15.7 and running into 
```
[INFO] [09-16|19:04:24.116] [3/16 Batches] Datastream disconnected. Ending the stage. 
[INFO] [09-16|19:04:24.116] [3/16 Batches] Finished Batches stage 
[INFO] [09-16|19:04:24.116] [4/16 BlockHashes] Etl transform started 
[INFO] [09-16|19:04:24.116] [4/16 BlockHashes] Nothing new to transform 
[INFO] [09-16|19:04:24.116] [4/16 BlockHashes] Etl transform ended 
[WARN] [09-16|19:04:51.417] Served                                   conn=192.168.0.7:45024 method=eth_call reqid=1 t=389.915µs err="invalid opcode: PUSH0"
[INFO] [09-16|19:05:22.402] [p2p] GoodPeers 
[INFO] [09-16|19:05:22.409] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=70.0MB sys=212.4MB
[INFO] [09-16|19:06:22.417] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=136.3MB sys=212.5MB
[WARN] [09-16|19:07:21.417] Served                                   conn=192.168.0.7:51880 method=eth_call reqid=1 t=1.578367ms err="invalid opcode: PUSH0"
[INFO] [09-16|19:07:22.403] [p2p] GoodPeers 
[INFO] [09-16|19:07:22.409] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=97.7MB sys=212.8MB
[INFO] [09-16|19:08:22.409] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=85.5MB sys=212.8MB
[INFO] [09-16|19:09:22.403] [p2p] GoodPeers 
[INFO] [09-16|19:09:22.408] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=74.6MB sys=212.8MB
[WARN] [09-16|19:09:51.417] Served                                   conn=192.168.0.7:51864 method=eth_call reqid=1 t=608.478µs err="invalid opcode: PUSH0"
```

**Comment by qk-santi** [comment]
We have synced 2 nodes from scratch on v1.2.15.7 and having this same issue

```
Sep 17 07:10:01 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: [INFO] [09-17|07:10:01.306] [9/16 IntermediateHashes] SMT regenerate progress: (98%)
Sep 17 07:10:11 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: [INFO] [09-17|07:10:11.306] [9/16 IntermediateHashes] SMT regenerate progress: (98%)
Sep 17 07:10:21 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: [INFO] [09-17|07:10:21.307] [9/16 IntermediateHashes] SMT regenerate progress: (99%)
Sep 17 07:10:31 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: [INFO] [09-17|07:10:31.256] [9/16 IntermediateHashes] Finished the temp tree build in 5m9.949430452s, hashing and saving the result...
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: [INFO] [09-17|07:10:36.211] [9/16 IntermediateHashes] Regeneration ended
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: [INFO] [09-17|07:10:36.211] [9/16 IntermediateHashes] Trie root      hash=0xbed25c06980247b6c30f0e7b8364b480b00a8439c68ea939a9c35967c1f10109
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: panic: [9/16 IntermediateHashes] Wrong trie root of block 6720712: bed25c06980247b6c30f0e7b8364b480b00a8439c68ea939a9c35967c1f10109, expected (from header): b0195a8089f2868b21761229f7db81bab33a5aa402a71174629eb17ab7a8fac4. Block hash: 806a366966e887da8b4a4efdef35508182ebff3d19bbcaa31f578b90e6a59dff
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: goroutine 69 [running]:
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: github.com/ledgerwatch/erigon/zk/stages.SpawnZkIntermediateHashesStage(0xc003b46bc0, {0x2f15e78?, 0xc000056048?}, {0x0, 0x0}, {{0x2f28898, 0xc000192b60}, 0x1, 0x0, {0xc002385f38, ...}, ...}, ...)
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]:         github.com/ledgerwatch/erigon/zk/stages/stage_interhashes.go:173 +0x125f
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func25(0x90?, 0x7?, 0x27818cf?, {0x2efda40?, 0xc003f10790?}, {0x0?, 0x0?}, 0x60?)
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]:         github.com/ledgerwatch/erigon/zk/stages/stages.go:379 +0x93
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc003f10790, 0xc0044f0410, {0x2f28898?, 0xc000192b60}, {0x0?, 0x0}, 0xb0?, 0x21?, 0x5?)
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]:         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:360 +0x16d
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc003f10790, {0x2f28898, 0xc000192b60}, {0x0, 0x0}, 0x2?, 0x0?)
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]:         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:262 +0x285
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2f15e40?, 0xc00017e3c0}, 0x8c31567b66a80966?, {0x2f28898, 0xc000192b60}, 0xc003f10790, 0xc001891140, 0x1, 0xc000a582f0)
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]:         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:177 +0x46d
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2f15e40, 0xc00017e3c0}, 0xc004351f50?, {0x2f28898?, 0xc000192b60}, 0xf9380e?, 0xc00195f8c0, 0xc00407a600?, 0xc0018918c0?, 0xc0000f6540, ...)
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]:         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:97 +0x165
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]: created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 cdk-erigon[5246]:         github.com/ledgerwatch/erigon/eth/backend.go:1422 +0x225
Sep 17 07:10:36 zkevm-cardona-rpc-ora-iad-e00 systemd[1]: cdk-erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

After restarting it continues from the block it excepted, starts the SMT regeneration on this new set of blocks, and excepts again.
But there's also a warning when opening the mdbx database.

```
[...]
[INFO] [09-17|07:10:44.324] Opening Database                         label=chaindata path=/data/erigon/chaindata
mdbx_setup_dxb:15946 filesize mismatch (expect 15032385536b/1835008p, have 27917287424b/3407872p)
[...]
[INFO] [09-17|07:10:46.051] [1/16 L1Syncer] Starting L1 sync stage
[INFO] [09-17|07:10:46.051] Starting L1 syncer thread
[INFO] [09-17|07:10:46.314] [1/16 L1Syncer] Saving L1 syncer progress latestCheckedBlock=6707667 newVerificationsCount=1 newSequencesCount=1 highestWrittenL1BlockNo=6707639
[INFO] [09-17|07:10:46.314] [1/16 L1Syncer]                          highestVerificationBatchNo=125312
[INFO] [09-17|07:10:46.345] [1/16 L1Syncer] Finished L1 sync stage
[INFO] [09-17|07:10:46.345] [2/16 L1InfoTree] Starting L1 Info Tree stage
[INFO] [09-17|07:10:46.345] Starting L1 syncer thread
[INFO] [09-17|07:10:46.529] [2/16 L1InfoTree] Info tree updates      count=0
[INFO] [09-17|07:10:46.529] [2/16 L1InfoTree] Finished L1 Info Tree stage
[INFO] [09-17|07:10:46.529] [3/16 Batches] Starting batches stage
[INFO] [09-17|07:10:46.529] [3/16 Batches] Starting stream           startBlock=6720712
[INFO] [09-17|07:10:46.529] [3/16 Batches] Reading blocks from the datastream.
[INFO] [09-17|07:10:46.529] [3/16 Batches] Started downloading L2Blocks routine
[INFO] [09-17|07:10:47.361] [3/16 Batches] No new blocks in 508 miliseconds. Ending the stage. lastBlockHeight=6720856
[INFO] [09-17|07:10:47.372] [3/16 Batches] Total blocks read: 144
[INFO] [09-17|07:10:47.372] [3/16 Batches] Saving stage progress     lastBlockHeight=6720856
[INFO] [09-17|07:10:47.372] [3/16 Batches] Finished writing blocks   blocksWritten=144 elapsed=842.920432ms
[INFO] [09-17|07:10:47.377] [3/16 Batches] Finished Batches stage
[INFO] [09-17|07:10:47.377] [4/16 BlockHashes] Etl transform started
[INFO] [09-17|07:10:47.379] [4/16 BlockHashes] Etl transform ended
[INFO] [09-17|07:10:47.379] [5/16 Senders] Started                   from=6720712 to=6720856
[INFO] [09-17|07:10:47.380] [5/16 Senders] Finished
[INFO] [09-17|07:10:47.380] [6/16 Execution] Blocks execution        from=6720712 to=6720856
[INFO] [09-17|07:10:47.419] [6/16 Execution] Commiting DB transaction... block=6720856
[INFO] [09-17|07:10:47.424] [6/16 Execution] Completed on            block=6720856
[INFO] [09-17|07:10:47.424] [7/16 CumulativeIndex] Started
[INFO] [09-17|07:10:47.426] [7/16 CumulativeIndex] Finished
[INFO] [09-17|07:10:47.426] [8/16 HashState] Started
[INFO] [09-17|07:10:47.426] [8/16 HashState] Promoting plain state   from=6720712 to=6720856
[INFO] [09-17|07:10:47.426] [8/16 HashState] Incremental promotion   from=6720712 to=6720856 codes=true csbucket=AccountChangeSet
[INFO] [09-17|07:10:47.426] [8/16 HashState] Incremental promotion   from=6720712 to=6720856 codes=false csbucket=AccountChangeSet
[INFO] [09-17|07:10:47.426] [8/16 HashState] Incremental promotion   from=6720712 to=6720856 codes=false csbucket=StorageChangeSet
[INFO] [09-17|07:10:47.436] [8/16 HashState] Finished
[INFO] [09-17|07:10:47.436] [9/16 IntermediateHashes] Generating intermediate hashes from=0 to=6720856
[INFO] [09-17|07:10:47.436] [9/16 IntermediateHashes] SMT not using mapmutation
[INFO] [09-17|07:10:47.436] [9/16 IntermediateHashes] Regeneration trie hashes started
[INFO] [09-17|07:10:47.436] [9/16 IntermediateHashes] Collecting account data...
[INFO] [09-17|07:10:58.208] [9/16 IntermediateHashes] SMT regenerate progress: (12%)
[INFO] [09-17|07:11:08.208] [9/16 IntermediateHashes] SMT regenerate progress: (23%)
```


Those 2 issues raises some concerns about the consistency of the database.

**Comment by qk-santi** [comment]
We have synced 2 nodes from scratch on `v1.2.15.7` and having this same issue

```
[INFO] [09-17|07:10:01.306] [9/16 IntermediateHashes] SMT regenerate progress: (98%)
[INFO] [09-17|07:10:11.306] [9/16 IntermediateHashes] SMT regenerate progress: (98%)
[INFO] [09-17|07:10:21.307] [9/16 IntermediateHashes] SMT regenerate progress: (99%)
[INFO] [09-17|07:10:31.256] [9/16 IntermediateHashes] Finished the temp tree build in 5m9.949430452s, hashing and saving the result...
[INFO] [09-17|07:10:36.211] [9/16 IntermediateHashes] Regeneration ended
[INFO] [09-17|07:10:36.211] [9/16 IntermediateHashes] Trie root      hash=0xbed25c06980247b6c30f0e7b8364b480b00a8439c68ea939a9c35967c1f10109
panic: [9/16 IntermediateHashes] Wrong trie root of block 6720712: bed25c06980247b6c30f0e7b8364b480b00a8439c68ea939a9c35967c1f10109, expected (from header): b0195a8089f2868b21761229f7db81bab33a5aa402a71174629eb17ab7a8fac4. Block hash: 806a366966e887da8b4a4efdef35508182ebff3d19bbcaa31f578b90e6a59dff
goroutine 69 [running]:
github.com/ledgerwatch/erigon/zk/stages.SpawnZkIntermediateHashesStage(0xc003b46bc0, {0x2f15e78?, 0xc000056048?}, {0x0, 0x0}, {{0x2f28898, 0xc000192b60}, 0x1, 0x0, {0xc002385f38, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/zk/stages/stage_interhashes.go:173 +0x125f
github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func25(0x90?, 0x7?, 0x27818cf?, {0x2efda40?, 0xc003f10790?}, {0x0?, 0x0?}, 0x60?)
        github.com/ledgerwatch/erigon/zk/stages/stages.go:379 +0x93
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc003f10790, 0xc0044f0410, {0x2f28898?, 0xc000192b60}, {0x0?, 0x0}, 0xb0?, 0x21?, 0x5?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:360 +0x16d
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc003f10790, {0x2f28898, 0xc000192b60}, {0x0, 0x0}, 0x2?, 0x0?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:262 +0x285
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2f15e40?, 0xc00017e3c0}, 0x8c31567b66a80966?, {0x2f28898, 0xc000192b60}, 0xc003f10790, 0xc001891140, 0x1, 0xc000a582f0)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:177 +0x46d
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2f15e40, 0xc00017e3c0}, 0xc004351f50?, {0x2f28898?, 0xc000192b60}, 0xf9380e?, 0xc00195f8c0, 0xc00407a600?, 0xc0018918c0?, 0xc0000f6540, ...)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:97 +0x165
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:1422 +0x225
cdk-erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

After restarting it continues from the block it excepted, starts the SMT regeneration on this new set of blocks, and excepts again.
But there's also a warning when opening the mdbx database.

```
[...]
[INFO] [09-17|07:10:44.324] Opening Database                         label=chaindata path=/data/erigon/chaindata
mdbx_setup_dxb:15946 filesize mismatch (expect 15032385536b/1835008p, have 27917287424b/3407872p)
[...]
[INFO] [09-17|07:10:46.051] [1/16 L1Syncer] Starting L1 sync stage
[INFO] [09-17|07:10:46.051] Starting L1 syncer thread
[INFO] [09-17|07:10:46.314] [1/16 L1Syncer] Saving L1 syncer progress latestCheckedBlock=6707667 newVerificationsCount=1 newSequencesCount=1 highestWrittenL1BlockNo=6707639
[INFO] [09-17|07:10:46.314] [1/16 L1Syncer]                          highestVerificationBatchNo=125312
[INFO] [09-17|07:10:46.345] [1/16 L1Syncer] Finished L1 sync stage
[INFO] [09-17|07:10:46.345] [2/16 L1InfoTree] Starting L1 Info Tree stage
[INFO] [09-17|07:10:46.345] Starting L1 syncer thread
[INFO] [09-17|07:10:46.529] [2/16 L1InfoTree] Info tree updates      count=0
[INFO] [09-17|07:10:46.529] [2/16 L1InfoTree] Finished L1 Info Tree stage
[INFO] [09-17|07:10:46.529] [3/16 Batches] Starting batches stage
[INFO] [09-17|07:10:46.529] [3/16 Batches] Starting stream           startBlock=6720712
[INFO] [09-17|07:10:46.529] [3/16 Batches] Reading blocks from the datastream.
[INFO] [09-17|07:10:46.529] [3/16 Batches] Started downloading L2Blocks routine
[INFO] [09-17|07:10:47.361] [3/16 Batches] No new blocks in 508 miliseconds. Ending the stage. lastBlockHeight=6720856
[INFO] [09-17|07:10:47.372] [3/16 Batches] Total blocks read: 144
[INFO] [09-17|07:10:47.372] [3/16 Batches] Saving stage progress     lastBlockHeight=6720856
[INFO] [09-17|07:10:47.372] [3/16 Batches] Finished writing blocks   blocksWritten=144 elapsed=842.920432ms
[INFO] [09-17|07:10:47.377] [3/16 Batches] Finished Batches stage
[INFO] [09-17|07:10:47.377] [4/16 BlockHashes] Etl transform started
[INFO] [09-17|07:10:47.379] [4/16 BlockHashes] Etl transform ended
[INFO] [09-17|07:10:47.379] [5/16 Senders] Started                   from=6720712 to=6720856
[INFO] [09-17|07:10:47.380] [5/16 Senders] Finished
[INFO] [09-17|07:10:47.380] [6/16 Execution] Blocks execution        from=6720712 to=6720856
[INFO] [09-17|07:10:47.419] [6/16 Execution] Commiting DB transaction... block=6720856
[INFO] [09-17|07:10:47.424] [6/16 Execution] Completed on            block=6720856
[INFO] [09-17|07:10:47.424] [7/16 CumulativeIndex] Started
[INFO] [09-17|07:10:47.426] [7/16 CumulativeIndex] Finished
[INFO] [09-17|07:10:47.426] [8/16 HashState] Started
[INFO] [09-17|07:10:47.426] [8/16 HashState] Promoting plain state   from=6720712 to=6720856
[INFO] [09-17|07:10:47.426] [8/16 HashState] Incremental promotion   from=6720712 to=6720856 codes=true csbucket=AccountChangeSet
[INFO] [09-17|07:10:47.426] [8/16 HashState] Incremental promotion   from=6720712 to=6720856 codes=false csbucket=AccountChangeSet
[INFO] [09-17|07:10:47.426] [8/16 HashState] Incremental promotion   from=6720712 to=6720856 codes=false csbucket=StorageChangeSet
[INFO] [09-17|07:10:47.436] [8/16 HashState] Finished
[INFO] [09-17|07:10:47.436] [9/16 IntermediateHashes] Generating intermediate hashes from=0 to=6720856
[INFO] [09-17|07:10:47.436] [9/16 IntermediateHashes] SMT not using mapmutation
[INFO] [09-17|07:10:47.436] [9/16 IntermediateHashes] Regeneration trie hashes started
[INFO] [09-17|07:10:47.436] [9/16 IntermediateHashes] Collecting account data...
[INFO] [09-17|07:10:58.208] [9/16 IntermediateHashes] SMT regenerate progress: (12%)
[INFO] [09-17|07:11:08.208] [9/16 IntermediateHashes] SMT regenerate progress: (23%)
```


Those 2 issues raises some concerns about the consistency of the database.

**Comment by hdiass** [comment]
Can you guys provide any update here ? Isn't this the official zkevm software now ?

**Comment by V-Staykov** [comment]
We are working on it. Currently syncing from scratch to try and reproduce it.

**Comment by hdiass** [comment]
What if this was mainnet ? you guys would need to sync from scratch to reproduce ?

**Comment by V-Staykov** [comment]
Not necessarily , but when we don't get the same problem, we try to reproduce it the way it was reported.

**Comment by hdiass** [comment]
So i had a node that got healthy, and from nowhere it restarted to do same thing

**Comment by qk-santi** [comment]
got a node in sync with `v2.0.0-beta18.2` with a bunch of `batch end state root mismatches last block's` which are supposedly fine to be ignored

**Comment by V-Staykov** [comment]
@hdiass Could you share config with which you launch a node? I can't seem to get the same errors with mine.

**Comment by hdiass** [comment]
> got a node in sync with `v2.0.0-beta18.2` with a bunch of `batch end state root mismatches last block's` which are supposedly fine to be ignored

Was able to sync too with this version.

**Comment by hdiass** [comment]
@V-Staykov Config file
```
      datadir: /database
      chain: hermez-cardona
      zkevm.l2-chain-id: 2442
      zkevm.l2-sequencer-rpc-url: https://rpc.cardona.zkevm-rpc.com/
      zkevm.l2-datastreamer-url: datastream.cardona.zkevm-rpc.com:6900
      zkevm.l1-chain-id: 11155111

      zkevm.address-sequencer: "0x761d53b47334bee6612c0bd1467fb881435375b2"
      zkevm.address-zkevm: "0xA13Ddb14437A8F34897131367ad3ca78416d6bCa"
      zkevm.address-admin: "0xff6250d0e86a2465b0c1bf8e36409503d6a26963"
      zkevm.address-rollup: "0x32d33d5137a7cffb54c5bf8371172bcec5f310ff"
      zkevm.address-ger-manager: "0xAd1490c248c5d3CbAE399Fd529b79B42984277DF"

      zkevm.default-gas-price: 1000000000
      zkevm.max-gas-price: 0
      zkevm.gas-price-factor: 0.12

      zkevm.l1-rollup-id: 1
      zkevm.l1-block-range: 20000
      zkevm.l1-query-delay: 6000
      zkevm.l1-first-block: 4789190
      txpool.disable: true
      torrent.port: 42070
      zkevm.datastream-version: 2

      externalcl: true
```
command and args
```
command:
    - cdk-erigon
  args:
    - --config
    - /node/config.yaml
    - --zkevm.l1-rpc-url
    - https://mynode
    - --zkevm.rpc-ratelimit=250
    - --maxpeers
    - "32"
    - --downloader.disable.ipv6
    - --http
    - --http.api
    - eth,net,trace,web3,erigon,zkevm
    - --http.addr
    - "0.0.0.0"
    - --http.port
    - "8545"
    - --http.vhosts=*
    - --http.corsdomain=*
    - --ws
    - --metrics
    - --metrics.addr
    - "0.0.0.0"
    - --port=$EXTERNAL_PORT_0
    - --nat=extip:$EXTERNAL_IP
    
```

**Comment by V-Staykov** [comment]
Okay, I've spoken with the team and there has been a problem with 18.3 release. The one currently should not be used.

Please use 18.2 until we release 18.4

**Comment by hexoscott** [comment]
Just to add to this, we just created 18.4 now which is a mirror of 18.2.  Done purely to save problems for anybody using the "latest" tag in Docker.  Let's close this issue down and can re-open if the issue persists but we've have confirmations from a number of sources now that 18.2 (and by extension 18.4) sync Cardona well.

**Comment by hdiass** [comment]
One thing i'd like to add is that this happened first on v1.2.15.7

**Comment by hexoscott** [comment]
Thanks for the heads up!
