### ISSUE TITLE
panic: state root mismatch on Cardona

### ISSUE THREAD

**Issue by frangrech** [0xPolygon/cdk-erigon#364]
#### System information

Erigon version: cdk-erigon version 2.43.0-dev-571fa2ff (latest zkevm branch commit), but seeing the same with v1.0.6

OS & Version: Ubuntu 22.04.4

Commit hash: 571fa2ff7d0e44aad1f1bdcfb507456a083bc3b7

Erigon Command (with flags/config):
```
cdk-erigon \
--config config.yaml \
--metrics \
--metrics.addr 0.0.0.0 \
--metrics.port 6060 \
--rpc.gascap 0
```

config.yaml:
```
datadir: /erigon/data
chain: hermez-cardona
http: true
private.api.addr: localhost:9092
zkevm.l2-chain-id: 2442
zkevm.l2-sequencer-rpc-url: https://rpc.cardona.zkevm-rpc.com/
zkevm.l2-datastreamer-url: datastream.cardona.zkevm-rpc.com:6900
zkevm.l1-chain-id: 11155111
zkevm.l1-rpc-url: <l1_url>

zkevm.address-sequencer: ""
zkevm.address-zkevm: ""
zkevm.address-admin: "0x32d33D5137a7cFFb54c5Bf8371172bcEc5f310ff"
zkevm.address-rollup: "0xA13Ddb14437A8F34897131367ad3ca78416d6bCa"
zkevm.address-ger-manager: "0xAd1490c248c5d3CbAE399Fd529b79B42984277DF"

zkevm.default-gas-price: 1
zkevm.max-gas-price: 0
zkevm.gas-price-factor: 0.12

zkevm.l1-rollup-id: 1
zkevm.l1-block-range: 20000
zkevm.l1-query-delay: 6000
zkevm.l1-first-block: 4789190
zkevm.rpc-ratelimit: 0
txpool.disable: true
torrent.port: 42070
zkevm.datastream-version: 2

externalcl: true
http.api: [eth, debug, net, trace, web3, erigon, zkevm]
http.addr: 0.0.0.0
http.vhosts: any
http.corsdomain: any
ws: true
```

Chain/Network: Polygon zkEVM Testnet (Cardona)

#### Expected behaviour
Node keeps syncing normally.

#### Actual behaviour
After getting in sync, after some time, usually 30-60m, the node errors with "panic: state root mismatch" and stops syncing. This first happened at block 2703371.

#### Steps to reproduce the behaviour
Sync a node on Cardona from scratch.

#### Backtrace

````
[EROR] [05-02|20:31:31.308] [1/15 L1Syncer] State root mismatch in block 2799636. Local=0x235fbfee452f696d2b1d583897cd0e3a70d24c5181ef4ebe750eb4ca2d94c7db, L1 verification=0xc6e632cae8a422e507fb40270ad63f41d13313ffa999acb3739f2d05b340baf2
[INFO] [05-02|20:31:31.308] [1/15 L1Syncer] Finished L1 sync stage
panic: state root mismatch
goroutine 136 [running]:
github.com/ledgerwatch/erigon/zk/stages.SpawnStageL1Syncer(0x2ea8760?, {0xc009f27da0?, 0x262feb0?}, {0x2ea4560, 0xc00080c550}, {0x2ece9e0, 0xc009f27da0}, {{0x2eb6c38, 0xc000134a80}, {0x2eb0160, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/zk/stages/stage_l1syncer.go:200 +0x176e
github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func1(0xd0?, 0x64?, 0x262feb0?, {0x2e8c240?, 0xc000d964d0?}, {0x2ece9e0?, 0xc009f27da0?}, 0x80?)
        github.com/ledgerwatch/erigon/zk/stages/stages.go:265 +0x88
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc000d964d0, 0xc00062ca00, {0x2eb6c38?, 0xc000134a80}, {0x2ece9e0?, 0xc009f27da0}, 0x2?, 0x6d?, 0xf8?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358 +0x16d
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc000d964d0, {0x2eb6c38, 0xc000134a80}, {0x2ece9e0, 0xc009f27da0}, 0xc0?, 0x4c?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260 +0x285
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2ea4560?, 0xc00080c550}, 0x0?, {0x2eb6c38, 0xc000134a80}, 0xc000d964d0, 0xc000d9f060, 0x0, 0xc0001cc260)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169 +0x42e
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2ea4560, 0xc00080c550}, 0xc001275f50?, {0x2eb6c38?, 0xc000134a80}, 0xf9208e?, 0xc000702d80, 0xc00127f020?, 0xc001275fb8?, 0xc0001025a0, ...)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95 +0x165
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:1338 +0x213
````

**Comment by hexoscott** [comment]
This issue has been resolved in the latest changes on zkevm branch.  Please re-open if you still experience this.
