### ISSUE TITLE
[RPC] State hash mismatch and sync halts

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/cdk-erigon#453]
#### System information

Erigon version: `./erigon --version`
``` cdk-erigon version 2.43.0-dev-fbf97ebf ```
OS & Version: Windows/Linux/OSX
``` Linux ```
Commit hash: 
``` fbf97ebf ```

Erigon Command (with flags/config):
``` ./build/bin/cdk-erigon --config="./xlayerconfig-mainnet.yaml"  ```
Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 
XLayer mainnet
#### Expected behaviour
The node should always sync to the latest block.

#### Actual behaviour
The node encounters a mismatch in the diff state hash and halts.

#### Steps to reproduce the behaviour
Offen occur XLayer mainnnet.
This issue frequently occurs on the XLayer mainnet. After restarting cdk-erigon, it returns to normal and resumes syncing.

#### Backtrace

````
[INFO] [05-23|05:37:41.953] [8/15 IntermediateHashes] Increment trie hashes started previousRootHeight=1538764 calculatingRootHeight=1538765
[INFO] [05-23|05:37:42.010] [8/15 IntermediateHashes] Regeneration trie hashes finished. Commiting batch
[INFO] [05-23|05:37:42.010] [8/15 IntermediateHashes] Increment ended
[INFO] [05-23|05:37:42.010] [8/15 IntermediateHashes] Trie root      hash=0x9c87e065ae50693e6ebc69a69d39e1bc7efab746b7e06cb22e8192207c40ee52
[INFO] [05-23|05:37:42.010] [8/15 IntermediateHashes] State root matches
[INFO] [05-23|05:37:42.489] [9/15 CallTraces] Started
[INFO] [05-23|05:37:42.491] [9/15 CallTraces] Finished
[INFO] [05-23|05:37:42.491] [10/15 AccountHistoryIndex] Started
[INFO] [05-23|05:37:42.491] [10/15 AccountHistoryIndex] Finished
[INFO] [05-23|05:37:42.491] [11/15 StorageHistoryIndex] Started
[INFO] [05-23|05:37:42.492] [11/15 StorageHistoryIndex] Finished
[INFO] [05-23|05:37:42.492] [12/15 LogIndex] Started
[INFO] [05-23|05:37:42.493] [12/15 LogIndex] Finished
[INFO] [05-23|05:37:42.493] [14/15 DataStream] Starting...
[INFO] [05-23|05:37:42.493] [14/15 DataStream] no streamer provided, skipping stage
[INFO] [05-23|05:37:42.493] [15/15 Finish] Started
[INFO] [05-23|05:37:42.493] [15/15 Finish] Finished
[INFO] [05-23|05:37:42.503] Commit cycle                             in=9.784626ms
[INFO] [05-23|05:37:42.503] Timings (slower than 50ms)               Batches=2.243s Execution=288ms IntermediateHashes=536ms
[INFO] [05-23|05:37:42.503] Tables                                   PlainState=340.6MB AccountChangeSet=275.6MB StorageChangeSet=742.3MB BlockTransaction=1.2GB TransactionLog=628.9MB FreeList=272.0KB ReclaimableSpace=272.0MB
[INFO] [05-23|05:37:42.503] RPC Daemon notified of new headers       from=1538764 to=1538765 hash=0xce8f8c1c7368181651a6a9ee2ad5475ac4438c8caedae94b6a46224be13d3d36 header sending=41.305µs log sending=535ns
[INFO] [05-23|05:37:42.503] [1/15 L1Syncer] Starting L1 sync stage
[INFO] [05-23|05:37:42.503] [1/15 L1Syncer] No new L1 blocks to sync
[INFO] [05-23|05:37:42.503] [1/15 L1Syncer] Finished L1 sync stage
[INFO] [05-23|05:37:42.503] [2/15 Batches] Starting batches stage
[INFO] [05-23|05:37:42.504] [2/15 Batches] Reading blocks from the datastream.
[INFO] [05-23|05:37:44.917] [2/15 Batches] No new blocks in 501 miliseconds. Ending the stage. lastBlockHeight=1538766
[INFO] [05-23|05:37:44.917] [2/15 Batches] Total blocks read: 1
[INFO] [05-23|05:37:44.917] [2/15 Batches] Finished writing blocks   blocksWritten=1 elapsed=2.413459921s
[INFO] [05-23|05:37:44.917] [2/15 Batches] Saving stage progress     lastBlockHeight=1538766
[INFO] [05-23|05:37:44.917] [2/15 Batches] Finished Batches stage
[INFO] [05-23|05:37:44.917] [3/15 BlockHashes] Etl transform started
[INFO] [05-23|05:37:44.917] [3/15 BlockHashes] Etl transform ended
[INFO] [05-23|05:37:45.190] [5/15 Execution] Short circuit           batch=27653 block=1538766
[INFO] [05-23|05:37:45.190] [5/15 Execution] Blocks execution        from=1538765 to=1538766
[INFO] [05-23|05:37:45.236] [5/15 Execution] Completed on            block=1538766
[INFO] [05-23|05:37:45.236] [6/15 CumulativeIndex] Started
[INFO] [05-23|05:37:45.236] [6/15 CumulativeIndex] Finished
[INFO] [05-23|05:37:45.236] [7/15 HashState] Started
[INFO] [05-23|05:37:45.260] [7/15 HashState] Finished
[INFO] [05-23|05:37:45.260] [8/15 IntermediateHashes] Increment trie hashes started previousRootHeight=1538765 calculatingRootHeight=1538766
[INFO] [05-23|05:37:45.563] [8/15 IntermediateHashes] Regeneration trie hashes finished. Commiting batch
[INFO] [05-23|05:37:45.563] [8/15 IntermediateHashes] Increment ended
[INFO] [05-23|05:37:45.563] [8/15 IntermediateHashes] Trie root      hash=0x422b1f288dafc081fafb9cd6c0bcef9e12b9c0e48e258596374c06f9b44ad183
panic: [8/15 IntermediateHashes] Wrong trie root of block 1538766: 422b1f288dafc081fafb9cd6c0bcef9e12b9c0e48e258596374c06f9b44ad183, expected (from header): a6bd170e199f3562fc8fd56d9366c21090d948ed685e2cabbe3adf845bcbb5ef. Block hash: 763f6e8b14af96975966eedf4e5616684cb34dc1c74cd16f04b83d46f5553b2d

goroutine 182 [running]:
github.com/ledgerwatch/erigon/zk/stages.SpawnZkIntermediateHashesStage(0xc006f1cd00, {0xc00855bf20?, 0x270b478?}, {0x2eb2490, 0xc00855bf20}, {{0x2e9a5d8, 0xc0000daa80}, 0x1, 0x0, {0xc00106e4f0, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/zk/stages/stage_interhashes.go:161 +0xf94
github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func22(0x10?, 0xa2?, 0x270b478?, {0x2e6fca0?, 0xc0008ca210?}, {0x2eb2490?, 0xc00855bf20?}, 0x80?)
        github.com/ledgerwatch/erigon/zk/stages/stages.go:343 +0x93
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0008ca210, 0xc00010e5f0, {0x2e9a5d8?, 0xc0000daa80}, {0x2eb2490?, 0xc00855bf20}, 0x22?, 0xc5?, 0xf6?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358 +0x16d
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0008ca210, {0x2e9a5d8, 0xc0000daa80}, {0x2eb2490, 0xc00855bf20}, 0x20?, 0x66?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260 +0x285
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2e87f60?, 0xc00089adc0}, 0x0?, {0x2e9a5d8, 0xc0000daa80}, 0xc0008ca210, 0xc0005a7d60, 0x0, 0xc0004ec670)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169 +0x42e
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2e87f60, 0xc00089adc0}, 0x0?, {0x2e9a5d8?, 0xc0000daa80}, 0xfc804e?, 0xc0014b46c0, 0x2e84120?, 0xc001afc600?, 0xc0000ba540, ...)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95 +0x165
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:1349 +0x225
Already up to date.
Building cdk-erigon

````

**Comment by zjg555543** [comment]
Maybe related https://github.com/0xPolygonHermez/cdk-erigon/pull/451
I will check it again.

**Comment by mandrigin** [comment]
@zjg555543 please let me know if that is fixed. Otherwise, we will investigate.

**Comment by zjg555543** [comment]
> Maybe related #451 I will check it again.
The issue still appears again with the correct rollup ID.

**Comment by zjg555543** [comment]
> @zjg555543 please let me know if that is fixed. Otherwise, we will investigate.

I am checking it today.

It's only apprears on xlayer mainnet. Interesting

**Comment by zjg555543** [comment]
It's only apprears on xlayer mainnet. Interesting

**Comment by zjg555543** [comment]
Will close this issue now. It does't appear again.

I test with latest batch  which based commit hash [2d23b85](https://github.com/okx/xlayer-erigon/commits/zjg/sync-halt/) and adding logs, the mismatch didn't  encounter agagin. 

**test result:**
**network**: xlayer mainnet
**server**: 2 cdk-erigon servers, mac and linux
**test duration**: 2 days
**result**: do not appear again
