### ISSUE TITLE
[Sequencer] RPC state root mismatches when runnning tests funding “scalable” smart contract.

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#466]
See Network 2.

```
Network2 @John Hilliard reported its down after first txs.
zkevm2-rpc-1  | [INFO] [05-23|16:14:34.673] [8/15 IntermediateHashes] Increment trie hashes started previousRootHeight=8550 calculatingRootHeight=8554
zkevm2-rpc-1  | [EROR] [05-23|16:14:34.680] RPC method debug_traceTransaction crashed: runtime error: invalid memory address or nil pointer dereference
zkevm2-rpc-1  | [service.go:217 panic.go:884 panic.go:260 signal_unix.go:841 state_transition.go:337 state_transition.go:199 state_processor_zkevm.go:78 tracing_zkevm.go:103 tracing.go:258 value.go:586 value.go:370 service.go:222 handler.go:511 handler.go:444 handler.go:392 handler.go:186 asm_amd64.s:1598] 
zkevm2-rpc-1  | [INFO] [05-23|16:14:34.688] [8/15 IntermediateHashes] Regeneration trie hashes finished. Commiting batch 
zkevm2-rpc-1  | [INFO] [05-23|16:14:34.688] [8/15 IntermediateHashes] Increment ended 
zkevm2-rpc-1  | [INFO] [05-23|16:14:34.688] [8/15 IntermediateHashes] Trie root      hash=0x8f2891959a9a6db9c59edd10d719cf0d62a4dea3a3c2df36ce8de707174c86fb
zkevm2-rpc-1  | panic: [8/15 IntermediateHashes] Wrong trie root of block 8554: 8f2891959a9a6db9c59edd10d719cf0d62a4dea3a3c2df36ce8de707174c86fb, expected (from header): 2e9b9eaa7441d41523deeb13831b750b7ee7180f66c78c34f26660221b716d32. Block hash: 6561975d57f7e797f925256e426b320897f01559a7562f71cc0c5242940c61f8
zkevm2-rpc-1  | 
zkevm2-rpc-1  | goroutine 38 [running]:
zkevm2-rpc-1  | github.com/ledgerwatch/erigon/zk/stages.SpawnZkIntermediateHashesStage(0xc006a4b540, {0xc008051c80?, 0x273142c?}, {0x2eda5d0, 0xc008051c80}, {{0x2ec2718, 0xc0001b8b60}, 0x1, 0x0, {0xc001a26d80, ...}, ...}, ...)
zkevm2-rpc-1  |         github.com/ledgerwatch/erigon/zk/stages/stage_interhashes.go:158 +0xf34
zkevm2-rpc-1  | github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func22(0x0?, 0xe0?, 0x273142c?, {0x2e97d20?, 0xc00620e000?}, {0x2eda5d0?, 0xc008051c80?}, 0x60?)
zkevm2-rpc-1  |         github.com/ledgerwatch/erigon/zk/stages/stages.go:343 +0x93
zkevm2-rpc-1  | github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc00620e000, 0xc000b6ae60, {0x2ec2718?, 0xc0001b8b60}, {0x2eda5d0?, 0xc008051c80}, 0xc2?, 0x80?, 0xf8?)
zkevm2-rpc-1  |         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358 +0x16d
zkevm2-rpc-1  | github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc00620e000, {0x2ec2718, 0xc0001b8b60}, {0x2eda5d0, 0xc008051c80}, 0x20?, 0x76?)
zkevm2-rpc-1  |         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260 +0x285
zkevm2-rpc-1  | github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2eb0040?, 0xc0007c20a0}, 0x0?, {0x2ec2718, 0xc0001b8b60}, 0xc00620e000, 0xc0017072a0, 0x0, 0xc0017021a0)
zkevm2-rpc-1  |         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169 +0x42e
zkevm2-rpc-1  | github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2eb0040, 0xc0007c20a0}, 0x0?, {0x2ec2718?, 0xc0001b8b60}, 0x0?, 0xc00161d8c0, 0x0?, 0x0?, 0xc0005a81e0, ...)
zkevm2-rpc-1  |         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95 +0x165
zkevm2-rpc-1  | created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
zkevm2-rpc-1  |         github.com/ledgerwatch/erigon/eth/backend.go:1341 +0x225
```

**Comment by mandrigin** [comment]
Couldn’t reproduce for now. We will run the full test suite locally.

**Comment by V-Staykov** [comment]
We ran the full test suite locally a few times and it seems okay. There was one point where we got a state root mismatch, but it is not reproducible. It might've been some coincidence and not directly linked to the tests.

**Comment by mandrigin** [comment]
Okay okay, let’s close it for now and see when we can find this mismatch.
