### ISSUE TITLE
[RPC] Wrong trie root

### ISSUE THREAD

**Issue by xzav3r** [0xPolygon/cdk-erigon#467]
#### System information

Erigon version: `./erigon --version`

OS & Version: Linux

Commit hash: fbf97ebf85e96ac749a857e625e2bc8edcd964e1

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: X Layer mainnet

#### Actual behaviour
The two RPC nodes unexpectedly crashed at the same height after running stably for several hours.

#### Backtrace

````
[backtrace]
panic: [8/15 IntermediateHashes] Wrong trie root of block 1565528: 4a53e0c540e7f73299c3672da91657c554484594a14dd89109c2dc120305c569, expected (from header): 4b0eecb641ea2e5b59be9b184d8b786cd86d94de799024c9db89b9ce7ff9c09f. Block hash: 0e8fc7c7cc16ada9c891dd305942f75da084abb072e63e790b9d739b843d7cbf

goroutine 97 [running]:
[github.com/ledgerwatch/erigon/zk/stages.SpawnZkIntermediateHashesStage](http://github.com/ledgerwatch/erigon/zk/stages.SpawnZkIntermediateHashesStage)(0xc00dd32000, {0xc00a9ad680?, 0x2729bed?}, {0x2ee2c90, 0xc00a9ad680}, {{0x2ecadd8, 0xc002021880}, 0x1, 0x0, {0xc001bf95f0, ...}, ...}, ...)
	[github.com/ledgerwatch/erigon/zk/stages/stage_interhashes.go:158](http://github.com/ledgerwatch/erigon/zk/stages/stage_interhashes.go:158) +0xf34
[github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func22](http://github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func22)(0x60?, 0x1?, 0x2729bed?, {0x2ea03e0?, 0xc005680160?}, {0x2ee2c90?, 0xc00a9ad680?}, 0x80?)
	[github.com/ledgerwatch/erigon/zk/stages/stages.go:343](http://github.com/ledgerwatch/erigon/zk/stages/stages.go:343) +0x93
[github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage](http://github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage)(0xc005680160, 0xc003a7e410, {0x2ecadd8?, 0xc002021880}, {0x2ee2c90?, 0xc00a9ad680}, 0xc2?, 0x81?, 0xf8?)
	[github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358](http://github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358) +0x16d
[github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run](http://github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run)(0xc005680160, {0x2ecadd8, 0xc002021880}, {0x2ee2c90, 0xc00a9ad680}, 0x20?, 0xe0?)
	[github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260](http://github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260) +0x285
[github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep](http://github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep)({0x2eb8700?, 0xc001e94780}, 0x0?, {0x2ecadd8, 0xc002021880}, 0xc005680160, 0xc0039afae0, 0x0, 0xc000cd20e0)
	[github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169](http://github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169) +0x42e
[github.com/ledgerwatch/erigon/turbo/stages.StageLoop](http://github.com/ledgerwatch/erigon/turbo/stages.StageLoop)({0x2eb8700, 0xc001e94780}, 0xe49860?, {0x2ecadd8?, 0xc002021880}, 0xc0007f2120?, 0xc000c24000, 0x1451606?, 0xc00055a798?, 0xc0005d60c0, ...)
	[github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95](http://github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95) +0x165
created by [github.com/ledgerwatch/erigon/eth.(*Ethereum).Start](http://github.com/ledgerwatch/erigon/eth.(*Ethereum).Start)
	[github.com/ledgerwatch/erigon/eth/backend.go:1334](http://github.com/ledgerwatch/erigon/eth/backend.go:1334) +0x213
````

**Comment by Sharonbc01** [comment]
Hi @yann-sjtu can you tell me which RPC milestone this items should be linked to please?

**Comment by xzav3r** [comment]
> Hi @yann-sjtu can you tell me which RPC milestone this items should be linked to please?

maybe `RPC on mainnet` milestone?

**Comment by xzav3r** [comment]
same as https://github.com/0xPolygonHermez/cdk-erigon/issues/453

**Comment by zjg555543** [comment]
It's only apprears on xlayer mainnet. Interesting

**Comment by zjg555543** [comment]
It doesn't not appear again.
Will close this issue now. https://github.com/0xPolygonHermez/cdk-erigon/issues/453

**Comment by SwatGuard** [comment]
Seeing this every day on hermeznetwork/cdk-erigon:v1.0.10 on xlayer mainnet. Using in house L1 RPC.
