### ISSUE TITLE
[Sequencer] L1InjectedBatch not found in sequencing stage

### ISSUE THREAD

**Issue by xzav3r** [0xPolygon/cdk-erigon#478]
#### System information

Erigon version: `./erigon --version`

OS & Version: Linux

Commit hash: 2d23b85a1192afc71702d619fd08c8224365823c

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 

#### Actual behaviour
It panics if sequencer is started before `L1FirstBlock` height of L1. And it can not recover after being restarted after `L1FirstBlock`.

#### Backtrace

````
[backtrace]
[INFO] [05-27|15:52:00.971] [4/12 Execution] Starting sequencing stage
[INFO] [05-27|15:52:00.971] [HermezDbReader] GetL1InjectedBatch:
[INFO] [05-27|15:52:00.971] [4/12 Execution] Finished sequencing stage
panic: runtime error: slice bounds out of range [:8] with capacity 0

goroutine 272 [running]:
github.com/ledgerwatch/erigon/zk/types.(*L1InjectedBatch).Unmarshall(0xc0001ba060?, {0x0?, 0x25?, 0x3?})
	github.com/ledgerwatch/erigon/zk/types/zk_types.go:103 +0x3fe
github.com/ledgerwatch/erigon/zk/hermez_db.(*HermezDbReader).GetL1InjectedBatch(0xc000629520, 0x0)
	github.com/ledgerwatch/erigon/zk/hermez_db/db.go:1015 +0x1ca
github.com/ledgerwatch/erigon/zk/stages.processInjectedInitialBatch({_, _}, {{0x2ee5c38, 0xc0001efea0}, 0x10000000, {0x1, {0x2ed9980, 0xc002cc6288}, {0x2ed9980, 0xc002cc62d0}, ...}, ...}, ...)
	github.com/ledgerwatch/erigon/zk/stages/stage_sequence_execute_injected_batch.go:35 +0x7b
github.com/ledgerwatch/erigon/zk/stages.SpawnSequencingStage(_, {_, _}, {_, _}, _, {_, _}, {{0x2ee5c38, 0xc0001efea0}, ...}, ...)
	github.com/ledgerwatch/erigon/zk/stages/stage_sequence_execute.go:83 +0x7bc
github.com/ledgerwatch/erigon/zk/stages.SequencerZkStages.func10(0xb0?, 0x40?, 0x26474c6?, {0x2ebb260?, 0xc003e340b0?}, {0x0?, 0x0?}, 0xa0?)
	github.com/ledgerwatch/erigon/zk/stages/stages.go:91 +0x9b
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc003e340b0, 0xc00085aa50, {0x2ee5c38?, 0xc0001efea0}, {0x0?, 0x0}, 0xa0?, 0x17?, 0xe7?)
	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358 +0x16d
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc003e340b0, {0x2ee5c38, 0xc0001efea0}, {0x0, 0x0}, 0x1?, 0x0?)
	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260 +0x285
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2ed35c0?, 0xc000d09c70}, 0x1?, {0x2ee5c38, 0xc0001efea0}, 0xc003e340b0, 0xc003bc95a0, 0x1, 0xc000ac8d60)
	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169 +0x42e
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2ed35c0, 0xc000d09c70}, 0x1?, {0x2ee5c38?, 0xc0001efea0}, 0x0?, 0xc0003c6000, 0x1?, 0x1?, 0xc0005e60c0, ...)
	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95 +0x165
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
	github.com/ledgerwatch/erigon/eth/backend.go:1356 +0x225
````

**Comment by xzav3r** [comment]
https://github.com/0xPolygonHermez/cdk-erigon/pull/479

It can automatically recover if we restart it after L1FirstBlock

**Comment by mandrigin** [comment]
Okay, merged your PR, closing this task. @yann-sjtu ping me if anything else needs to be done here.
