### ISSUE TITLE
[Sequencer] Panic when attempting to communicate with an offline executor

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#542]
[EROR] [06-05|03:41:59.797] error getting verifier result            err="failed to process stateless batch: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 34.175.214.161:50076: connect: connection refused\""
[EROR] [06-05|03:42:00.057] error getting verifier result            err="no executor available"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101506824]

goroutine 263 [running]:
github.com/ledgerwatch/erigon/zk/legacy_executor_verifier.(*LegacyExecutorVerifier).ConsumeResultsUnsafe(0x1400032b680, {0x102b8ce60?, 0x1240058cd380})
	github.com/ledgerwatch/erigon/zk/legacy_executor_verifier/legacy_executor_verifier.go:247 +0x94
github.com/ledgerwatch/erigon/zk/stages.SpawnSequencerExecutorVerifyStage(0x1?, {0x18?, 0x140007f79e8?}, {0x102b8ce60, 0x1240058cd380?}, {0x102b66d00, 0x14000e59540}, {{0x102b788b8?, 0x140002de7e0?}, 0x1400032b680?, ...}, ...)
	github.com/ledgerwatch/erigon/zk/stages/stage_sequencer_executor_verify.go:92 +0x1ac
github.com/ledgerwatch/erigon/zk/stages.SequencerZkStages.func13(0x70?, 0x83?, 0x101e1c974?, {0x102b4f300?, 0x14001308370?}, {0x102b8ce60?, 0x1240058cd380?}, 0xe0?)
	github.com/ledgerwatch/erigon/zk/stages/stages.go:104 +0x6c
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0x14001308370, 0x14002b7c460, {0x102b788b8?, 0x140002de7e0}, {0x102b8ce60?, 0x1240058cd380}, 0xc8?, 0x9b?, 0xbc?)
	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358 +0xec
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0x14001308370, {0x102b788b8, 0x140002de7e0}, {0x102b8ce60, 0x1240058cd380}, 0x10?, 0x7e?)
	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260 +0x20c
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x102b66d00?, 0x14000e59540}, 0x0?, {0x102b788b8, 0x140002de7e0}, 0x14001308370, 0x14001398de0, 0x0, 0x140005ae230)
	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169 +0x318
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x102b66d00, 0x14000e59540}, 0x102b71e20?, {0x102b788b8?, 0x140002de7e0}, 0x3?, 0x14000e14000, 0x0?, 0x0?, 0x1010f1730?, ...)
	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95 +0xd8
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
	github.com/ledgerwatch/erigon/eth/backend.go:1360 +0x1e0

**Comment by hexoscott** [comment]
fixed by #557
