### ISSUE TITLE
X Layer - Node crashing - panic: [9/16 IntermediateHashes] Wrong trie root of block

### ISSUE THREAD

**Issue by andreclaro** [0xPolygon/cdk-erigon#644]
#### Description
Node is crashing in loop with `panic: [9/16 IntermediateHashes] Wrong trie root of block`

#### System information

Erigon version: `./erigon --version`
```
cdk-erigon --version
[cdk-erigon-lib] timestamp 2024-03-12:16:34
cdk-erigon version 2.43.0-dev-3e3013f2
```

OS & Version: Ubuntu

Erigon Command (with flags/config):

```
/usr/local/bin/cdk-erigon \
    --datadir /var/lib/xlayer/data/erigon \
    --chain xlayer-mainnet \
    --private.api.addr localhost:9091 \
    --zkevm.l2-chain-id 196 \
    --zkevm.l2-sequencer-rpc-url https://rpc.xlayer.tech \
    --zkevm.l2-datastreamer-url stream.xlayer.tech:8800 \
    --zkevm.l1-chain-id 1 \
    --zkevm.l1-rpc-url http://10.86.0.60:8545 \
    --zkevm.address-sequencer "" \
    --zkevm.address-zkevm "" \
    --zkevm.address-admin "0x5132a183e9f3cb7c848b0aac5ae0c4f0491b7ab2" \
    --zkevm.address-rollup "0x2B0ee28D4D51bC9aDde5E58E295873F61F4a0507" \
    --zkevm.address-ger-manager "0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb" \
    --zkevm.l1-rollup-id 3 \
    --zkevm.l1-first-block 19218658 \
    --zkevm.l1-block-range 100 \
    --zkevm.l1-query-delay 6000 \
    --zkevm.rpc-ratelimit 250 \
    --zkevm.datastream-version 2 \
    --externalcl \
    --http \
    --http.api "eth,debug,net,trace,web3,erigon,zkevm" \
    --http.addr 0.0.0.0 \
    --http.port 8545 \
    --http.vhosts "*" \
    --ws \
    --metrics \
    --metrics.addr 0.0.0.0 \
    --metrics.port 6060 \
    --authrpc.addr 127.0.0.1 \
    --authrpc.port 8551 \
    --authrpc.jwtsecret /var/lib/xlayer/jwt.hex
```

Chain/Network: X Layer Mainner

#### Backtrace

````
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.039] [1/16 L1Syncer] Starting L1 sync stage
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.039] Starting L1 syncer thread
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.060] [1/16 L1Syncer] No new L1 blocks to sync
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.061] [1/16 L1Syncer] Finished L1 sync stage
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.061] [2/16 L1InfoTree] Starting L1 Info Tree stage
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.061] Starting L1 syncer thread
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.083] [2/16 L1InfoTree] Info tree updates      count=0
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.083] [2/16 L1InfoTree] Finished L1 Info Tree stage
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.083] [3/16 Batches] Starting batches stage
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.083] [3/16 Batches] Starting stream           startBlock=2308902
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.083] [3/16 Batches] Reading blocks from the datastream.
Jun 18 21:10:09 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:09.083] [3/16 Batches] Started downloading L2Blocks routine
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.195] [3/16 Batches] No new blocks in 501 miliseconds. Ending the stage. lastBlockHeight=2308907
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.195] [3/16 Batches] Total blocks read: 5
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.196] [3/16 Batches] Finished writing blocks   blocksWritten=5 elapsed=1.112739194s
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.196] [3/16 Batches] Saving stage progress     lastBlockHeight=2308907
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.216] [3/16 Batches] Finished Batches stage
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.216] [4/16 BlockHashes] Etl transform started
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.222] [4/16 BlockHashes] Etl transform ended
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.227] [6/16 Execution] Blocks execution        from=2308902 to=2308907
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.236] [6/16 Execution] Commiting DB transaction... block=2308907
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.277] [6/16 Execution] Completed on            block=2308907
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.277] [7/16 CumulativeIndex] Started
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.281] [7/16 CumulativeIndex] Finished
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.281] [8/16 HashState] Started
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.299] [8/16 HashState] Finished
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.299] [9/16 IntermediateHashes] Generating intermediate hashes from=2307921 to=2308907
Jun 18 21:10:10 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:10.299] [9/16 IntermediateHashes] Increment trie hashes started previousRootHeight=2307921 calculatingRootHeight=2308907
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:11.769] [9/16 IntermediateHashes] Regeneration trie hashes finished. Commiting batch
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:11.769] [9/16 IntermediateHashes] Increment ended
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: [INFO] [06-18|21:10:11.769] [9/16 IntermediateHashes] Trie root      hash=0xc1887f35f10b96137d827ad77a4d1d5690b87a0ae2a61b3df093c3afc02760c2
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: panic: [9/16 IntermediateHashes] Wrong trie root of block 2308907: c1887f35f10b96137d827ad77a4d1d5690b87a0ae2a61b3df093c3afc02760c2, expected (from header): 960fc753d916a97acfeda5c5bb0755bd65c56910643eadd1319fbe7aba9730de. Block hash: bcc06ac0c7758d59d5471ddc0b0d476cd3c695f0deef8a47566ac6bb214b6cb7
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: goroutine 125 [running]:
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: github.com/ledgerwatch/erigon/zk/stages.SpawnZkIntermediateHashesStage(0xc0008e5500, {0x2ef2548?, 0xc000054070?}, {0x0, 0x0}, {{0x2f0c6f0, 0xc000f00540}, 0x1, 0x0, {0xc000555260, ...}, ...}, ...)
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]:         github.com/ledgerwatch/erigon/zk/stages/stage_interhashes.go:161 +0x1074
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func25(0x60?, 0x61?, 0x270eec7?, {0x2ecf2e0?, 0xc0041e6160?}, {0x0?, 0x0?}, 0x40?)
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]:         github.com/ledgerwatch/erigon/zk/stages/stages.go:348 +0x93
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc0041e6160, 0xc000752500, {0x2f0c6f0?, 0xc000f00540}, {0x0?, 0x0}, 0xe0?, 0x61?, 0xeb?)
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]:         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358 +0x16d
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc0041e6160, {0x2f0c6f0, 0xc000f00540}, {0x0, 0x0}, 0x0?, 0x0?)
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]:         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260 +0x285
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2ef2510?, 0xc002be1900}, 0x40?, {0x2f0c6f0, 0xc000f00540}, 0xc0041e6160, 0xc00054b460, 0x1, 0xc00035b330)
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]:         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169 +0x42e
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2ef2510, 0xc002be1900}, 0xc0000a9020?, {0x2f0c6f0?, 0xc000f00540}, 0xc000932fd0?, 0xc000ef2480, 0xc0005ba140?, 0xc00414a000?, 0xc000f08120, ...)
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]:         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95 +0x165
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]: created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
Jun 18 21:10:11 m-xlayer-01 cdk-erigon[3951725]:         github.com/ledgerwatch/erigon/eth/backend.go:1357 +0x225
Jun 18 21:10:11 m-xlayer-01 systemd[1]: cdk-erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 18 21:10:11 m-xlayer-01 systemd[1]: cdk-erigon.service: Failed with result 'exit-code'.
Jun 18 21:10:11 m-xlayer-01 systemd[1]: cdk-erigon.service: Consumed 4.266s CPU time.
````

**Comment by andreclaro** [comment]
Tried to delete database and run the node from genesis but the node is still crashing with `Wrong trie root of block` error after completed "[9/16 IntermediateHashes] SMT regenerate" stage.

Full logs:
```
Jun 18 23:24:49 m-xlayer-01 cdk-erigon[1785]: [INFO] [06-18|23:24:49.825] [9/16 IntermediateHashes] SMT regenerate progress: (92%)
Jun 18 23:24:59 m-xlayer-01 cdk-erigon[1785]: [INFO] [06-18|23:24:59.833] [9/16 IntermediateHashes] SMT regenerate progress: (93%)
Jun 18 23:25:09 m-xlayer-01 cdk-erigon[1785]: [INFO] [06-18|23:25:09.825] [9/16 IntermediateHashes] SMT regenerate progress: (95%)
Jun 18 23:25:19 m-xlayer-01 cdk-erigon[1785]: [INFO] [06-18|23:25:19.825] [9/16 IntermediateHashes] SMT regenerate progress: (97%)
Jun 18 23:25:29 m-xlayer-01 cdk-erigon[1785]: [INFO] [06-18|23:25:29.825] [9/16 IntermediateHashes] SMT regenerate progress: (98%)
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: [INFO] [06-18|23:25:37.342] [9/16 IntermediateHashes] Finished the temp tree build in 5m17.516841372s, hashing and saving the result...
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: [INFO] [06-18|23:25:37.342] [9/16 IntermediateHashes] Regeneration ended
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: [INFO] [06-18|23:25:37.342] [9/16 IntermediateHashes] Trie root      hash=0xccdfbca674af0a3bc56bb13fb298691f67eb0a9d3b048b1411a1ec9465590414
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: panic: [9/16 IntermediateHashes] Wrong trie root of block 2308708: ccdfbca674af0a3bc56bb13fb298691f67eb0a9d3b048b1411a1ec9465590414, expected (from header): a013300559434290287554784fa11b6e090290102cd54d1c6c082da45e7aa80e. Block hash: 8d4562d5a6f3f4085deb6ad351228ec141607e8b6f84bbbcd543b89639a7ed9a
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: goroutine 195 [running]:
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: github.com/ledgerwatch/erigon/zk/stages.SpawnZkIntermediateHashesStage(0xc006ab6480, {0x2ef2548?, 0xc000054080?}, {0x0, 0x0}, {{0x2f0c6f0, 0xc00131c700}, 0x1, 0x0, {0xc000897360, ...}, ...}, ...)
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]:         github.com/ledgerwatch/erigon/zk/stages/stage_interhashes.go:161 +0x1074
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func25(0x60?, 0x21?, 0x270eec7?, {0x2ecf2e0?, 0xc002552160?}, {0x0?, 0x0?}, 0x0?)
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]:         github.com/ledgerwatch/erigon/zk/stages/stages.go:348 +0x93
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc002552160, 0xc000a8ca00, {0x2f0c6f0?, 0xc00131c700}, {0x0?, 0x0}, 0x40?, 0x17?, 0x52?)
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]:         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:358 +0x16d
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc002552160, {0x2f0c6f0, 0xc00131c700}, {0x0, 0x0}, 0x80?, 0xa4?)
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]:         github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:260 +0x285
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x2ef2510?, 0xc000b707c0}, 0x0?, {0x2f0c6f0, 0xc00131c700}, 0xc002552160, 0xc001e48180, 0x1, 0xc0013604c0)
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]:         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:169 +0x42e
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2ef2510, 0xc000b707c0}, 0x1eeb2b9?, {0x2f0c6f0?, 0xc00131c700}, 0xc000b707c0?, 0xc0001d8900, 0xc00199c1e0?, 0x0?, 0xc0000c6720, ...)
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]:         github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:95 +0x165
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]: created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
Jun 18 23:25:37 m-xlayer-01 cdk-erigon[1785]:         github.com/ledgerwatch/erigon/eth/backend.go:1357 +0x225
Jun 18 23:25:38 m-xlayer-01 systemd[1]: cdk-erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 18 23:25:38 m-xlayer-01 systemd[1]: cdk-erigon.service: Failed with result 'exit-code'.
Jun 18 23:25:38 m-xlayer-01 systemd[1]: cdk-erigon.service: Consumed 2h 25min 375ms CPU time.
Jun 18 23:25:48 m-xlayer-01 systemd[1]: cdk-erigon.service: Scheduled restart job, restart counter is at 1.
Jun 18 23:25:48 m-xlayer-01 systemd[1]: Stopped "zkEVM CDK-Erigon service".
Jun 18 23:25:48 m-xlayer-01 systemd[1]: cdk-erigon.service: Consumed 2h 25min 375ms CPU time.
Jun 18 23:25:48 m-xlayer-01 systemd[1]: Started "zkEVM CDK-Erigon service".
```

**Comment by Zheaoli** [comment]
The same

**Comment by SwatGuard** [comment]
Same here.

**Comment by andreclaro** [comment]
This issue is impacting all node operators using cdk-erigon: 

![image](https://github.com/0xPolygonHermez/cdk-erigon/assets/33039405/f16c2b0c-d802-475c-bd35-a5d3c2d7557e)

**Comment by andreclaro** [comment]
CC: @mandrigin @giskook @zjg555543

**Comment by selverob** [comment]
In our case it crashes with the same basic error but the block on which it crashes `2321464` and on every crash, it advances by one or two blocks.

**Comment by Igor-rockawayx** [comment]
we are facing the same issue

**Comment by andreclaro** [comment]
I see this logic comment in the stage interhashes logic: https://github.com/0xPolygonHermez/cdk-erigon/blob/b43e4d2791d7d1d2cdc85b21b2255d476057be4e/zk/stages/stage_interhashes.go#L179-L183 

🤔

**Comment by corpocott** [comment]
same issue here

**Comment by dancamarg0** [comment]
Same issue here

**Comment by zjg555543** [comment]
Thank you for your feedback and patience. The datastream service has been fixed. You can try any of the following actions:
1. Delete the database and run the node from genesis.
2. Or re-download the snapshot. We are currently creating it, but it might take some time.([snapshot](https://static.okex.org/cdn/chain/xlayer/snapshot/index.html))

**Comment by andreclaro** [comment]
I'm following your suggestion (1) and will let you know if I see any issue. Thanks!

**Comment by zjg555543** [comment]
We also recommend that you enable both the zkevm node and the Erigon node as backups.

[zkevm rpc node](https://github.com/okx/Deploy/blob/main/mainnet/setup-zknode-rpc.md)

**Comment by andreclaro** [comment]
Our node is fully recovered and in-sync. Thanks

**Comment by mandrigin** [comment]
okay, we will still check it -- looks strange if it went away by itself. or was it related to datastream being wrong somehow?

also, I see it is not a release itself

**Comment by andreclaro** [comment]
I think this was related with issues with the data streamer, which happened after the network halt.

@zjg555543 can share more details :)

**Comment by mandrigin** [comment]
Ah, okay, so I will close that then. Please reopen if still happens.

**Comment by zjg555543** [comment]
The XLayer mainnet DS format had an issue, but it has been fixed by regenerating it.
@mandrigin @andreclaro

**Comment by sgrsaga** [comment]
@mandrigin I detected the same issue again.

Running version:
[cdk-erigon-lib] timestamp 2024-03-12:16:34
cdk-erigon/v2.61.3-RC1/linux-amd64/go1.21.13

Error:
`
[EROR] [02-07|04:32:02.456] Staged Sync                              err="[8/16 IntermediateHashes] Wrong trie root of block 8936099: d7a1744b25b051e300a6fa7a56fed849b15e160a5a93016d3fd6fab794bab52c, expected (from header): ca19733e5bd3efdfc3c6f3515c6982eb8b4419f9807b60e84747dbc573bd97f7. Block hash: 0b3c7ca840f929ccbbe7daea0b986b366a1dcf3423d5882babc61264968b6a2e, trace: [stageloop.go:105 panic.go:920 stage_interhashes.go:168 stages.go:348 sync.go:513 sync.go:383 stageloop.go:154 stageloop.go:73 asm_amd64.s:1650]"`

**Comment by pffont** [comment]
Same thing here with block 9245291

```
[cdk-erigon-lib] timestamp 2024-03-12:16:34
cdk-erigon/v2.61.1/linux-amd64/go1.22.0

```
