### ISSUE TITLE
panic: Contract address check failed

### ISSUE THREAD

**Issue by andreclaro** [0xPolygon/cdk-erigon#980]
#### Description

Got the error `panic: Contract address check failed` on testnet after the upgrade from `v1.2.15.2` to `v1.2.15.4`. To resolve the issue by using `v1.2.15.3` version. 

Node is now syncing. Latest log messate: 
```
cdk-erigon[60445]: [INFO] [08-17|10:41:36.223] [9/16 IntermediateHashes] SMT incremental progress: (88%)
```

On mainnet, I upgraded from `v1.2.15.2` to `v1.2.15.4` without observed issues.

#### System information

Erigon version: v1.2.15.4
- https://github.com/0xPolygonHermez/cdk-erigon/releases/tag/v1.2.15.4

OS & Version: Ubuntu 22.04.3 LTS

Erigon Command (with flags/config): 

```
/usr/local/bin/cdk-erigon \
    --datadir /var/lib/xlayer/data/erigon \
    --chain xlayer-testnet \
    --private.api.addr localhost:9091 \
    --zkevm.l2-chain-id 195 \
    --zkevm.l2-sequencer-rpc-url https://testrpc.xlayer.tech \
    --zkevm.l2-datastreamer-url teststream.xlayer.tech:8800 \
    --zkevm.l1-chain-id 11155111 \
    --zkevm.l1-rpc-url http://ETH_L1 \
    --zkevm.address-sequencer "0xD6DdA5AA7749142B7fDa3Fe4662C9f346101B8A6" \
    --zkevm.address-zkevm "0x01469dACfDDA885D68Ff0f8628F2629c14F95a20" \
    --zkevm.address-admin "0x14509f825e550745CFF827a9bDCCB4C3ad3FFd36" \
    --zkevm.address-rollup "0x6662621411A8DACC3cA7049C8BddABaa9a999ce3" \
    --zkevm.address-ger-manager "0x66E61bA00F58b857A9DD2C500F3aBc424A46BD20" \
    --zkevm.l1-rollup-id 1 \
    --zkevm.l1-first-block 4648290 \
    --zkevm.l1-block-range 2000 \
    --zkevm.l1-query-delay 1000 \
    --zkevm.rpc-ratelimit 250 \
    --zkevm.datastream-version 3 \
    --externalcl \
    --http \
    --http.api "eth,debug,net,trace,web3,erigon,zkevm" \
    --http.addr 0.0.0.0 \
    --http.port 8545 \
    --http.vhosts "*" \
    --ws \
    --metrics \
    --metrics.addr 0.0.0.0 \
    --metrics.port 6060 \
    --authrpc.addr 127.0.0.1 \
    --authrpc.port 8551 \
    --authrpc.jwtsecret /var/lib/xlayer/jwt.hex
```

#### Backtrace

````
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [cdk-erigon-lib] timestamp 2024-03-12:16:34
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:24.978] logging to file system                   log dir=/var/lib/xlayer/data/erigon/logs file prefix=erigon log level=info json=false
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:24.979] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics/prometheus
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:24.992] logging to file system                   log dir=/var/lib/xlayer/data/erigon/logs file prefix=cdk-erigon log level=info json=false
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:24.993] Build info                               git_branch=HEAD git_tag=tags/v1.2.15.4 git_commit=de3d03f20e27eeb106ed5b688df38b02d4c63a1c
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:24.993] Poseidon hashing                         Accelerated=true
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:24.993] Starting Erigon on                       devnet=xlayer-testnet
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:24.993] Maximum peer count                       ETH=100 total=100
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:24.994] starting HTTP APIs                       APIs=eth,debug,net,trace,web3,erigon,zkevm
Aug 17 10:33:24 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:24.994] torrent verbosity                        level=WRN
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:27.096] Set global gas cap                       cap=50000000
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:27.099] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=16mb upload.rate=4mb
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:27.099] Opening Database                         label=chaindata path=/var/lib/xlayer/data/erigon/chaindata
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:27.100] Initialised chain configuration          config="{ChainID: 195, Homestead: 0, DAO: 0, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 0, Muir Glacier: 0, Berlin: 0, London: 18446744073709551615, Arrow Glacier: 9999999999999999999999999999999999999999999999999, Gray Glacier: 9999999999999999999999999999999999999999999999999, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Shanghai: 18446744073709551615, Cancun: 18446744073709551615, Prague: 18446744073709551615, Engine: ethash}" genesis=0x22a8085892b367833bd7431fa5a90ff6b5d3769167cdaa29ce8571d07bc8f866
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:27.101] Effective                                prune_flags= snapshot_flags= history.v3=false
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:27.104] Initialising Ethereum protocol           network=195
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:27.104] Disk storage enabled for ethash DAGs     dir=/var/lib/xlayer/data/erigon/ethash-dags count=2
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:27.441] Starting private RPC server              on=localhost:9091
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [INFO] [08-17|10:33:27.447] new subscription to logs established
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: [WARN] [08-17|10:33:27.450] L1 contract address check failed (AddressAdmin) expected=0x14509f825e550745CFF827a9bDCCB4C3ad3FFd36 actual=0xC432168eF74A83c6E6C76f2c1b42F875E1A223CD
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: panic: Contract address check failed
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: goroutine 1 [running]:
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: github.com/ledgerwatch/erigon/eth.New(0xc00018a540, 0x417dcc0)
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]:         github.com/ledgerwatch/erigon/eth/backend.go:818 +0x6ac6
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: github.com/ledgerwatch/erigon/turbo/node.New(0xc00005e080?, 0x26de351?)
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]:         github.com/ledgerwatch/erigon/turbo/node/node.go:114 +0x74
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: main.runErigon(0xc00075a2c0?)
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]:         github.com/ledgerwatch/erigon/cmd/cdk-erigon/main.go:65 +0x295
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: github.com/urfave/cli/v2.(*Command).Run(0xc00075a2c0, 0xc00074fc00, {0xc000053800, 0x3d, 0x40})
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]:         github.com/urfave/cli/v2@v2.25.7/command.go:274 +0xa42
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: github.com/urfave/cli/v2.(*App).RunContext(0xc0002205a0, {0x2f49a28?, 0xc000054070}, {0xc000053800, 0x3d, 0x40})
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]:         github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x616
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: github.com/urfave/cli/v2.(*App).Run(...)
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]:         github.com/urfave/cli/v2@v2.25.7/app.go:309
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]: main.main()
Aug 17 10:33:27 t-xlayer-02 cdk-erigon[60157]:         github.com/ledgerwatch/erigon/cmd/cdk-erigon/main.go:39 +0x85
Aug 17 10:33:27 t-xlayer-02 systemd[1]: cdk-erigon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 17 10:33:27 t-xlayer-02 systemd[1]: cdk-erigon.service: Failed with result 'exit-code'.
````

**Comment by zjg555543** [comment]
Thanks for your sharing.I will check it now.

**Comment by zjg555543** [comment]
Fixed by https://github.com/0xPolygonHermez/cdk-erigon/pull/982.
Or replace it mannually like this:
```
zkevm.address-admin "0xC432168eF74A83c6E6C76f2c1b42F875E1A223CD"
```

**Comment by hexoscott** [comment]
Closing this one as the panic in this case is a safety check to stop the node running with incorrect configuration.

**Comment by andreclaro** [comment]
Thanks! It worked! Cheers
